### ISSUE TITLE
Implement Edit action on User list

### ISSUE THREAD

**Issue by abdullokhKhamzaev** [Abdullokh-dev/documentation#1]
**Task Description**
Create a form with required areas accordingly user properties.

**Acceptance Criteria**

- [ ] Modal form is ready
- [ ] Form is filling by default from Old User properties
- [ ] Add Validation to required areas
